version: '3'

# volumes:
#  db-volume: # windowsの場合はコメントを外す

services:
  cake-db:
    # platform: linux/x86_64 # M1チップの場合はコメントを外す
    container_name: cake-db
    image: mysql:8.0
    volumes:
      - ./volumes/mysql:/var/lib/mysql
      # - db-volume:/var/lib/mysql # windowsの場合はコメントを外し、上の行をコメントアウトする
      - ./mysql/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_DATABASE: "basercms"
    command: mysqld --character-set-server=utf8 --collation-server=utf8_general_ci --innodb-use-native-aio=0 --sql-mode=NO_ENGINE_SUBSTITUTION --default_authentication_plugin=mysql_native_password

  cake-php:
    container_name: cake-php
    image: baserproject/basercms:php8.1
    volumes:
      - ../:/var/www/html:delegated
#      - ../:/var/www/shared:delegated
    environment:
      PHP_IDE_CONFIG: "serverName=localhost"
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: "1"
      COMPOSER_ALLOW_SUPERUSER: 1
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - cake-db
    command: bash -c "/var/www/html/docker/bin/init.sh && apache2-foreground"
#    command: bash -c "/var/www/shared/docker/bin/init_lsyncd.sh && /var/www/shared/docker/bin/init.sh && apache2-foreground"

  cake-smtp:
    container_name: cake-smtp
    image: schickling/mailcatcher
    ports:
      - "1080:1080"
      - "1025:1025"

  cake-pma:
    container_name: cake-pma
    image: phpmyadmin
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=cake-db
      - PMA_USER=root
      - PMA_PASSWORD=root
    links:
      - cake-db
    ports:
     - 8080:80
    volumes:
       - ./phpmyadmin/sessions:/sessions
